# Command constants.
# ADD_USER: no arguments.
string ADD_USER = add_user
# KILL_USER: arguments = { id }
string KILL_USER = kill_user
# NUM_USERS: arguments = { }
string NUM_USERS = num_users
# USER_INFO: arguments = { id }
string USER_INFO = user_info
# PLAY: arguments = { }
string PLAY = play
# PAUSE_NOW: arguments = { }
string PAUSE_NOW = pause_now
# PAUSE_LATER: arguments = { }
string PAUSE_LATER = pause_later
# RESET_ROBOT: arguments = { }
string RESET_ROBOT = reset_robot
# LOAD_TASK: arguments = { task-file-name }
string LOAD_TASK = load_task
# LOAD_SCENE: arguments = { scene-file-name }
string LOAD_SCENE = load_scene
# SHOW_BASE_PATH: arguments = { [base-path-file-name] }
string SHOW_BASE_PATH = show_base_path
# LOAD_MESH: arguments = { mesh-file-name, movable, [mesh-name] }
string LOAD_MESH = load_mesh
# GRIPPER_CONTROLS: arguments = { [basic] }
string GRIPPER_CONTROLS = gripper_controls
# RESET_TASK: arguments = { }
string RESET_TASK = reset_task
# BEGIN_RECORDING: arguments = { [path] }
string BEGIN_RECORDING = begin_recording
# BEGIN_REPLAY: arguments = { file }
string BEGIN_REPLAY = begin_replay
# END_RECORDING: arguments = { }
string END_RECORDING = end_recording
# END_REPLAY: arguments = { }
string END_REPLAY = end_replay
# PROCESS_KEY: arguments = { key, type }
string PROCESS_KEY = process_key
# SET_BASE_SPEED: arguments = { linear, angular }
string SET_BASE_SPEED = set_base_speed
# SET_ARM_SPEED: arguments = { speed }
string SET_ARM_SPEED = set_arm_speed
# SET_FRAME_RATE: arguments = { rate }
string SET_FRAME_RATE = set_frame_rate
# CHANGE_GOAL: arguments = { new-goal-number }
string CHANGE_GOAL = change_goal
# ACCEPT_GRASP: arguments = { }
string ACCEPT_GRASP = accept_grasp
# SHOW_INTERACTIVE_GRIPPER = { goal-number }
string SHOW_INTERACTIVE_GRIPPER = show_interactive_gripper
# HIDE_INTERACTIVE_GRIPPER = { goal-number }
string HIDE_INTERACTIVE_GRIPPER = hide_interactive_gripper
# ROBOT_MARKER_CONTROL = { enabled }
string ROBOT_MARKER_CONTROL = robot_marker_control
# SET_JOINT_STATES = { }
string SET_JOINT_STATES = set_joint_states

# A valid string command.
string command
# A string array of arguments for the given command.
string[] args
---
# A string response from the server for the given command.
string response
